version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    volumes:
      - ./data/db/mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    depends_on:
      - db
    volumes:
      - "./app:/usr/src/app"
  nginx:
    container_name: nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - "./app:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    depends_on:
      - php

